### PR TITLE
Update to use Akka gRPC 0.5.0

### PR DESCRIPTION
**Pull request by marcospereira**
Depends on https://github.com/akka/akka-grpc/pull/524.

### CODE REVIEW

**Comment by raboof** [comment]
Hmm did travis not run for this PR? I though there were still some tests failing around response status codes.

We should definitely improve test coverage of that in akka-grpc upstream though, working on that. Also it's not obvious what to expect: it looks like it's reasonable to send a HTTP 200, but add a trailing `grpc-status` header to convey the error (https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses). That is what the code appears to do, but I'm not sure if I'm actually seeing this happening - hence working on testing that at the akka-grpc side now.

**Comment by dwijnand** [comment]
Argh, sorry.  I've seen PR checks false negative, so when I saw the checkmark on the commit I thought it was also green in the PR validation merge commit.

**Comment by marcospereira** [comment]
@dwijnand should we revert this merge? It is now blocking https://github.com/playframework/play-grpc/pull/54.

**Comment by raboof** [comment]
Perhaps 'roll forward' and disable the test checking for that 500 error code? Hm weird that it doesn't seem to find https://bintray.com/sbt/sbt-plugin-releases?filterByPkgName=sbt-akka-grpc btw

**Comment by dwijnand** [comment]
> @dwijnand should we revert this merge? It is now blocking #54.

I'm happy with revert or forward-fixing.

**Comment by marcospereira** [comment]
Rolling forward here: https://github.com/playframework/play-grpc/pull/55

**Pull request merged**
