### PR TITLE
Remove auto module for ClassicActorSystemProvider

### PR DESCRIPTION
**Pull request by octonato**
This is not compatible with Play 2.8.3 as Play has already a binding for `ClassicActorSystemProvider`. 

When enabled we get

```scala
A binding to akka.actor.ClassicActorSystemProvider was already configured at play.grpc.ClassicActorsystemProviderModule.<init>(ClassicActorsystemProviderModule.scala:13):
[error] Binding(interface akka.actor.ClassicActorSystemProvider to ProviderConstructionTarget(class play.api.libs.concurrent.ActorSystemProvider)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4).
```

Still in draft, needs to adapt the docs. 

I suggest we document that Play 2.8.3 users need to disable the module for now. 

```hocon
play.modules.disabled += "play.grpc.ClassicActorsystemProviderModule"
```

And as soon we cut a new Play gRPC we document the other way around.

References #317

### CODE REVIEW

**Comment by raboof** [comment]
> Play has already a binding for `ClassicActorSystemProvider`.

Perhaps we should just require Play 2.8.3 so we can simply assume it exist and doesn't need to be added here anymoe?

**Comment by raboof** [comment]
Could we delete `play.grpc.ClassicActorsystemProviderModule` and require Play 2.8.3?

**Comment by ignasi35** [comment]
@octonato I've reviewed this after our call and I think I agree with @raboof and prefer deleting the module.

Users of Play 2.8.2 or prior bumping play-grpc won't get a `ClassicActorSystemProvider` from either the Play or the play-grpc bindings but it's a oneliner they can add themselves. I think we can safely document the alternatives and delete the play-grpc module altogether.

**Comment by ignasi35** [comment]
Tests fail because the module is missing, maybe we can already require `2.8.3` in this PR and solve it all at once.

**Comment by octonato** [comment]
I agree in removing it. I will take that in consideration when moving this draft to ready for review.

**Comment by octonato** [comment]
@ignasi35, we may want to wait for 2.8.4 before we cut a new release here.

**Comment by octonato** [comment]
I did the updates as agreed, but without the documentation about how to create the module. 

I haven't done is because it's not a one-liner, as we said. There is Java and Scala and also Lagom users. So, maybe we can discuss this strategy a little more. 

Lagom users are bound to a fix Play version which is not 2.8.3 at the moment. Maybe the easiest is to keep the class and only document how to enable the module. 

Anyway, we are not in a hurry. Let's give more time to think and consider the options.

**Comment by ignasi35** [comment]
This is related to #312

**Comment by raboof** [comment]
> I did the updates as agreed, but without the documentation about how to create the module. I haven't done is because it's not a one-liner, as we said

Perhaps we should just document "this version of play-grpc requires at least play 2.8.3, so if you want an older version of play you need to stick to an older version of play-grpc"?

**Review by raboof — APPROVED** [review]

**Pull request merged**
