### PR TITLE
use fully qualified class name in generated module

### PR DESCRIPTION
**Pull request by cbcwebdev**
- users on short lived ugprade paths sometimes need to maintain {versionN-1, versionN} clients in an application. currently they receive ambiguous import compile errors.

pseudo example of issue may entail services as follows:

~~~
package foo.v1;

service FooService {}
~~~

~~~
package foo.v2;

service FooService {}
~~~

while not ideal, some applications may need an incremental upgrade path for breaking changes that span multiple modules, so both clients need to be available for a period of time

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @c-bowden,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by raboof — APPROVED** [review]
Makes sense to me (relates to https://github.com/akka/akka-grpc/issues/641)

**Comment by raboof** [comment]
I just checked the CLA database, and the signature for `cbcwebdev` is in there, but this commit was attributed to `c-bowden`. Do you want to sign the CLA with the `c-bowden` account as well, or change the commit to link to an email address that is associated with the `cbcwebdev` account?

**Comment by cbcwebdev** [comment]
> I just checked the CLA database, and the signature for `cbcwebdev` is in there, but this commit was attributed to `c-bowden`. Do you want to sign the CLA with the `c-bowden` account as well, or change the commit to link to an email address that is associated with the `cbcwebdev` account?

ill fix the commit shortly

**Comment by lightbend-cla-validator** [comment]
Hi @c-bowden,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Pull request closed without merging**
