### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by cuongthamhl**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @cuongthamhl,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by thecodecentral** [comment]
@marcospereira I am fine to close this PR and have someone else who is able to contribute to fix this issue. I am not going to sign the CLA at this time.

**Comment by cuongthamhl** [comment]
@marcospereira I am fine to close this PR and have someone who is able to contribute to fix the typo. I am not going to sign the CLA at this time.

**Comment by renatocaval** [comment]
I will fix it. Thanks @cuongthamhl for letting us know.

**Pull request closed without merging**
