### PR TITLE
Remove year from Copyright header

### PR DESCRIPTION
**Pull request by renatocaval**

### CODE REVIEW

**Comment by raboof** [comment]
(in akka-grpc I made `CurrentYear` static so we can update it at our convenience instead of having existing PR's start failing spontaneously, https://github.com/akka/akka-grpc/pull/778/files#diff-81069bae6b5b7d26f2bb7c2de77bbd4dR30)

**Comment by renatocaval** [comment]
@raboof, I agree. I even don't know why we are making this dynamic. Some of our builds are defined so, others have it just hard-coded. 

I don't see the advantage of having it in a variable though.
Why this: 

```scala
val CopyrightPattern = "Copyright \\([Cc]\\) (\\d{4}(-\\d{4})?) (Lightbend|Typesafe) Inc. <.*>".r
```

In some of our projects we have it defined as one single string, for instance:
```scala
headerLicense := Some(
  HeaderLicense.Custom(
  "Copyright (C) 2016-2020 Lightbend Inc. <https://www.lightbend.com>"
)
```

**Comment by raboof** [comment]
the pattern can be useful when you want to allow different files to have been introduced in different years IIRC - but indeed having `CurrentYear` separate might no longer make sense

**Comment by renatocaval** [comment]
@raboof, we decided to simplify it (a lot) by following the https://github.com/scala/scala example. 

We will simply not add any year to the headers.

**Pull request merged**
