### PR TITLE
upgrade akka grpc to 2.1.5

### PR DESCRIPTION
**Pull request by damonpu**
Upgrade akka grpc to 2.1.5, there are breaking changes in akka grpc

### CODE REVIEW

**Comment by mkurz** [comment]
Thanks, that should work :wink:

**Comment by damonpu** [comment]
@mkurz when do you think the latest code in the main branch can be released?

**Comment by mkurz** [comment]
@damonpu That should be possible I guess, probably as version 0.10.0. Not today probably, maybe next week? Please ping me again if I forget :wink:

**Comment by damonpu** [comment]
@mkurz I think it's better to bump the major version since Akka grpc upgrade Scala PB from 0.10 to 0.11 which is not binary compatible

**Comment by damonpu** [comment]
@mkurz Please do a new release when you have time. thank you

**Pull request merged**
